#include "AVLTree.h"
#include "ChainingHashTable.h"
#include "LinearArrayTable.h"
#include "LinkedListTable.h"
#include "MenuDesign.h"
#include "RehashingHashTable.h"
#include "Polinom.h"
#include "SortedArrayTable.h"
#include <TableManager.h>